### ISSUE TITLE
Experiment yaml validation - tutorial section 5.3

### ISSUE THREAD

**Issue by cherdeman** [dssg/dirtyduck#13]
I ran into an error below running the `./tutorial.sh triage --config_file inspections_dt.yaml validate` command to validate the yaml file before running the experiment. The fix is to update the 'tsrange' to 'daterange' in the `cohort_config` secton of the `inspections_dt.yaml` file. I think this change will be need to made in the other yaml config files as well.

```
Traceback (most recent call last):
  File "/usr/local/bin/triage_experiment", line 11, in <module>
    load_entry_point('triage-experiment', 'console_scripts', 'triage_experiment')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/triage_experiment/triage_experiment.py", line 77, in validate
    experiment.validate()
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 559, in validate
    ExperimentValidator(self.db_engine, strict=strict).run(self.config)
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/validate.py", line 601, in run
    experiment_config.get('cohort_config', {}))
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/validate.py", line 32, in run
    raise ValueError(e)
ValueError: 
                    Section: cohort_config -
                    given query can not be run with a sample as_of_date .
                    query: "select entity_id
from semantic.entities
where
tsrange(start_time, end_time, '[]') @> '{as_of_date}'::date
"
                    Full error: (psycopg2.ProgrammingError) operator does not exist: tsrange @> date
LINE 4: tsrange(start_time, end_time, '[]') @> '2016-01-01'::date
```

**Comment by nanounanue** [comment]
This is correct, It is related to a change in the default behaviour of `triage`
