### ISSUE TITLE
cannot import name 'FSModelStorageEngine'

### ISSUE THREAD

**Issue by pavel-trubitsyn** [dssg/dirtyduck#18]
Got the following after the 
> ./tutorial.sh triage --config_file simple_test_skeleton.yaml show_temporal_blocks

```
WARNING: Image for service triage was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/local/bin/triage_experiment", line 11, in <module>
    load_entry_point('triage-experiment', 'console_scripts', 'triage_experiment')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/triage_experiment/triage_experiment.py", line 11, in <module>
    from triage.component.catwalk.storage import FSModelStorageEngine
ImportError: cannot import name 'FSModelStorageEngine'

```

**Comment by ecsalomon** [comment]
This is an issue with inconsistent triage versions. It should be fixed in the upgrade_v3.0.2 branch (see #15). Try checking out that branch and rebuilding your docker containers. Let us know if you still encounter this error.

**Comment by pavel-trubitsyn** [comment]
Confirm, the upgrade_v3.0.2 branch is working with few fixes (triage_experiment --config_file and commands).

**Comment by ecsalomon** [comment]
Good to hear! Thanks!
