### ISSUE TITLE
Update Triage version in requirements

### ISSUE THREAD

**Issue by cherdeman** [dssg/dirtyduck#8]
I ran into this error when running the command `./tutorial.sh triage --help` in section 4.1 in the tutorial:

```
Traceback (most recent call last):
  File "/usr/local/bin/triage_experiment", line 11, in <module>
    load_entry_point('triage-experiment', 'console_scripts', 'triage_experiment')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/triage_experiment/triage_experiment.py", line 11, in <module>
    from triage.component.catwalk.storage import FSModelStorageEngine
ImportError: cannot import name 'FSModelStorageEngine'
```
Dirtyduck currently installs an old version of triage, the requirements.txt file in  dirtyduck/infrastructure/triage directory should be updated with:

```
## DSaPP stuff
git+https://github.com/dssg/triage.git@v3.beta
```

**Comment by nanounanue** [comment]
Closed in 9c8de4bd9fd5cf907bfa80f96cd9240fd47cfdb8
